// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"todolist/config"
	"todolist/internal/db"
	"todolist/internal/handler"
	"todolist/internal/repository"
	"todolist/internal/service"
)

// Injectors from wire.go:

func initializeApp() (*App, error) {
	configConfig := config.Load()
	gormDB, err := db.ProvideDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	todoRepository := repository.NewTodoRepository(gormDB)
	todoService := service.NewTodoService(gormDB, todoRepository)
	todoHandler := handler.NewTodoHandler(todoService)
	app := newApp(configConfig, todoHandler)
	return app, nil
}
